parameters:
- name: ort_version
  type: string

- name: build_config
  type: string
  default: 'Release'

# resources:
#   repositories:
#   - repository: onnxruntime-genai # The name used to reference this repository in the checkout step
#     type: github
#     name: microsoft/onnxruntime-genai

stages:
- stage: Build_Android_AAR
  jobs:
  - template: jobs/android-java-api-aar.yml
    parameters:
      ort_version: ${{ parameters.ort_version }}
      build_config: ${{ parameters.build_config }}
