name: "Linux GPU x64 Build"
on: [ workflow_dispatch, pull_request ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  ort_dir: "onnxruntime-linux-x64-gpu-1.16.3"
  ort_zip: "onnxruntime-linux-x64-gpu-1.16.3.tgz"
  ort_url: "https://github.com/microsoft/onnxruntime/releases/download/v1.16.3/onnxruntime-linux-x64-gpu-1.16.3.tgz"
  docker_image: "onnxruntimegpubuild"
jobs:
  job:
    name: "Linux GPU x64 Build"
    runs-on: [ "self-hosted", "1ES.Pool=onnxruntime-genai-Ubuntu2004-T4" ]
    steps:
      - name: Checkout OnnxRuntime GenAI repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Download OnnxRuntime
        run: |
          echo "Downloading ${{ env.ort_url }}"
          curl -L -o ${{ env.ort_zip }} ${{ env.ort_url }} 
          echo "Unzipping ${{ env.ort_zip }}"
          tar -xzf ${{ env.ort_zip }}
          rm ${{ env.ort_zip }}
          echo "Renaming ${{ env.ort_dir }} to ort"
          mv ${{ env.ort_dir }} ort

      - name: Get Docker Image
        run: |
          set -e -x
          python3 tools/ci_build/get_docker_image.py --dockerfile tools/ci_build/github/linux/docker/inference/x64/default/gpu/Dockerfile \
            --context tools/ci_build/github/linux/docker/inference/x64/default/gpu \
            --docker-build-args "--build-arg BUILD_UID=$( id -u )" \
            --container-registry onnxruntimebuildcache \
            --repository ${{ env.docker_image }}

      - name: Print Docker Image Environment Variables
        run: |
          echo "Printing docker image environment variables"
          docker run --rm ${{ env.docker_image }} env

      - name: Build with Cmake in Docker
        run: |
          echo "Running docker image ${{ env.docker_image }}"
          docker run \
            --gpus all \
            --rm \
            --volume $GITHUB_WORKSPACE:/onnxruntime_src \
            --volume $RUNNER_TEMP:/build \
            -w /build ${{ env.docker_image }} bash -c "/onnxruntime_src/extern/vcpkg/bootstrap-vcpkg.sh && /usr/bin/cmake -G Ninja /onnxruntime_src -DCMAKE_CUDA_ARCHITECTURES=75 -DUSE_CUDA=1 -DCMAKE_BUILD_TYPE=Release && ninja"

