name: "Windows CPU arm64 Build"
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - rel-*
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
env:
  ort_dir: "onnxruntime-win-arm64-1.16.3"
  ort_zip: "$(ort_dir).zip"
  ort_url: "https://github.com/microsoft/onnxruntime/releases/download/v1.16.3/$(ort_zip)"
#  VCPKG_FORCE_SYSTEM_BINARIES: "1"

jobs:
  job:
    runs-on: ["self-hosted", "1ES.Pool=onnxruntime-genai-Win11-ARM-CPU"]
    steps:
      - name: Checkout OnnxRuntime GenAI repo
        uses: actions/checkout@v4
        with:
          submodules: true
#      - name: Download latest Git
#        run: |
#          Invoke-WebRequest https://github.com/dennisameling/git/releases/download/v2.41.0.windows.1/PortableGit-2.41.0-arm64.7z.exe -OutFile ${{ github.workspace }}/git.exe
## This is needed for arm64 builds because the default action/checkout@v4 does not support submodules
#      - name: Checkout submodules
#        run: |
#          ${{ github.workspace }}/git.exe --version
#          ${{ github.workspace }}/git.exe submodule update --init --recursive

#      - uses: lukka/get-cmake@latest
      - uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{ github.workspace }}/extern/vcpkg
          runVcpkgInstall: true

      - name: Setup Visual Studio 2022
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: '17.4'
          msbuild-architecture: arm64

      - name: Download OnnxRuntime
        run: |
          $env:ort_url = "https://github.com/microsoft/onnxruntime/releases/download/v1.16.3/onnxruntime-win-arm64-1.16.3.zip"
          Invoke-WebRequest -Uri $env:ort_url -OutFile $env:ort_zip

      - name: Unzip OnnxRuntime
        run: |
          Expand-Archive $env:ort_zip -DestinationPath .
          Remove-Item -Path $env:ort_zip

      - name: Rename OnnxRuntime to ort
        run: |
          Rename-Item -Path $env:ort_dir -NewName ort

      - name: Build with CMake
        run: |
          cmake -G "Visual Studio 17 2022" -A arm64 . -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release --parallel

      - name: Verify Build Artifacts
        if: always()
        run: |
          Get-ChildItem -Path $env:GITHUB_WORKSPACE\Release -Recurse

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: onnxruntime-genai-win-cpu-arm64
          path: Release/*.lib
