on: [ workflow_dispatch, push, pull_request ]
env:
  ort_version: "1.16.3"
  ort_dir: "onnxruntime-win-x64-$(ort_version)"
  ort_zip: "$(ort_dir).zip"
  ort_url: "https://github.com/microsoft/onnxruntime/releases/download/v$(ort_version)/$(ort_zip)"

jobs:
  job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up Visual Studio 2022
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: '17.5'

      - name: Download OnnxRuntime
        run: |
          $env:ort_url = "https://github.com/microsoft/onnxruntime/releases/download/v1.16.3/onnxruntime-win-x64-1.16.3.zip"
          Invoke-WebRequest -Uri $env:ort_url -OutFile $env:ort_zip

      - name: Unzip OnnxRuntime
        run: |
          Expand-Archive $env:ort_zip -DestinationPath .
          Remove-Item -Path $env:ort_zip

      - name: Rename OnnxRuntime to ort
        run: |
          Rename-Item -Path $env:ort_dir -NewName ort

      - name: Git Submodule Update
        run: |
          git submodule update --init --recursive

      - name: Build with CMake
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" -A x64 ..
          cmake --build . --config Release --parallel
      - name: verify build folder
        run: |
          cd build
          Get-ChildItem -Path $env:GITHUB_WORKSPACE\build\Release -Recurse
#          TODO : adding shared library to the build
      
