on: [ workflow_dispatch, push, pull_request]
env:
    ort_dir: "onnxruntime-win-x64-1.16.3"
    ort_zip: ort_dir + ".zip"
    ort_url: "https://github.com/microsoft/onnxruntime/releases/download/v1.16.3/onnxruntime-win-x64-1.16.3.zip"

jobs:
  job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download OnnxRuntime
        run: |
          $env:ort_url = "https://github.com/microsoft/onnxruntime/releases/download/v1.16.3/onnxruntime-win-x64-1.16.3.zip"
          Invoke-WebRequest -Uri $env:ort_url -OutFile $env:ort_zip
      - name: Unzip OnnxRuntime
        run: |
          Expand-Archive $env:ort_zip -DestinationPath .
          Remove-Item -Path $env:ort_zip
          Get-ChildItem -Path $env:GITHUB_WORKSPACE
      
